kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: golang
    commands:
      - make install

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter

  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.1.0/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: test
    image: golang
    commands:
      - make test-coverage

  - name: build
    image: golang
    commands:
      - make build
      - make build-npm

  - name: github release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files:
        - ls-lint-darwin
        - ls-lint-linux
        - ls-lint-windows.exe
    when:
      event: tag

  - name: npm-darwin
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      folder: npm/ls-lint-darwin

  - name: npm-linux
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      folder: npm/ls-lint-linux

  - name: docker
    image: plugins/docker
    settings:
      username: loeffel-io
      password:
        from_secret: GITHUB_TOKEN
      dockerfile: docker/Dockerfile
      auto_tag: true
      repo: docker.pkg.github.com/ls-lint/ls-lint
      registry: docker.pkg.github.com