kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: golang
    commands:
      - make install

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter

  - name: test
    image: golang
    commands:
      - make test-coverage

  - name: build
    image: golang
    commands:
      - make build

  - name: github release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files:
        - ls-lint-darwin
        - ls-lint-linux
    when:
      event: tag