kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: golang
    commands:
      - make install

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter

  - name: ls-lint
    image: lslintorg/ls-lint
    commands:
      - ls-lint

  - name: test
    image: golang
    commands:
      - make test-coverage

  - name: build
    image: golang
    commands:
      - make build
      - make build-npm

  - name: github release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files:
        - ls-lint-darwin
        - ls-lint-linux
        - ls-lint-windows.exe
    when:
      event: tag

  - name: npm-darwin
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      folder: npm/ls-lint-darwin
    when:
      event: tag

  - name: npm-linux
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      folder: npm/ls-lint-linux
    when:
      event: tag

  - name: docker hub
    image: plugins/docker
    settings:
      username: loeffel
      password:
        from_secret: DOCKER_PASSWORD
      dockerfile: docker/Dockerfile
      auto_tag: true
      repo: lslintorg/ls-lint
    when:
      event: tag
