kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: golang
    commands:
      - make install

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter

  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.0.3/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: test
    image: golang
    commands:
      - make test-coverage

  - name: build
    image: golang
    commands:
      - make build

  - name: github release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files:
        - ls-lint-darwin
        - ls-lint-linux
    when:
      event: tag

  - name: npm-darwin
    image: plugins/npm
    commands:
      - mkdir -p npm/ls-lint-darwin/bin
      - cp ls-lint-darwin npm/ls-lint-darwin/bin/ls-lint
      - chmod +x npm/ls-lint-darwin/bin/ls-lint
      - ls -al npm/ls-lint-darwin
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      folder: npm/ls-lint-darwin