# https://github.com/vuejs/vue-next - b716a906fe51e82a1b3f82cf538b67abdaf66154

ls:
  .js: kebab-case | camelCase
  .ts: camelCase | PascalCase
  .d.ts: kebab-case
  .mock.ts: kebab-case
  .spec.ts: camelCase | PascalCase
  .test-d.ts: kebab-case
  .config.js: kebab-case
  .umd.js: kebab-case
  .spec.ts.snap: camelCase | PascalCase
  .global.js: kebab-case

ignore:
  - node_modules
  - .git
  - .circleci
  - .github
  - .vscode