# https://github.com/vuejs/vue-next - b716a906fe51e82a1b3f82cf538b67abdaf66154

ls:
  .js: kebab-case
  .ts: camelCase
  .d.ts: kebab-case
  .mock.ts: kebab-case
  .spec.ts: camelCase
  .test-d.ts: kebab-case
  .config.js: kebab-case
  .umd.js: kebab-case
  .spec.ts.snap: camelCase

  scripts:
    .js: camelCase

  packages/**/{components,collections}:
    .ts: PascalCase
    .spec.ts: PascalCase

ignore:
  - node_modules
  - .git
  - .circleci
  - .github
  - .vscode